### ISSUE TITLE
Confirmation avant génération QR code

### ISSUE THREAD

**Issue by bquiller** [EsupPortail/esup-otp-manager#19]
Bonjour,

Je pense qu'il serait bien qu'il y ait une confirmation lors du click sur le bouton generate_qrcode : l'action va désactiver le code précédent et les utilisateurs ne sont pas forcément conscients de cela.

Merci,
Brice.

**Comment by aanli** [comment]
Bonjour,
Merci Brice pour la remarque, c'est noté

Aymar

**Comment by aanli** [comment]
C'est implémenté dans le commit 
commit f462a5e45a20d350327bfa0c9dda3a0a837389d7
Author: Aymar Anli <Aymar.Anli@univ-paris1.fr>
Date:   Wed Dec 28 15:30:23 2022 +0100

    Confirm dialog before generate codes (bypass) and Qrcode (totp)
