### ISSUE TITLE
Conflit dans les dépendances 

### ISSUE THREAD

**Issue by egalantUBO** [EsupPortail/esup-otp-manager#23]
Bonjour, 
Losque nous faisons l'installation de l'application via npm install

Nous avons cette erreur suivante.

Bien cordialement,
Eric 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: passport-apereo-cas@0.2.0
npm ERR! Found: passport@0.6.0
npm ERR! node_modules/passport
npm ERR!   passport@"^0.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer passport@"^0.4.0" from passport-apereo-cas@0.2.0
npm ERR! node_modules/passport-apereo-cas
npm ERR!   passport-apereo-cas@"0.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: passport@0.4.1
npm ERR! node_modules/passport
npm ERR!   peer passport@"^0.4.0" from passport-apereo-cas@0.2.0
npm ERR!   node_modules/passport-apereo-cas
npm ERR!     passport-apereo-cas@"0.2.0" from the root project

**Comment by floriannari** [comment]
Bonjour,
normalement le problème est corrigé dans la branche https://github.com/EsupPortail/esup-otp-manager/tree/fix_dependencies_issues

(Nous pousserons dans Master d'ici quelques jours)
