### ISSUE TITLE
[random_code_mail] permettre de ne pas autoriser l'adresse email professionnelle 

### ISSUE THREAD

**Issue by floriannari** [EsupPortail/esup-otp-manager#26]
> Nous aimerions empêcher les utilisateurs d'utiliser leur adresse mail professionnelle dans le manager car on perd tout l'intérêt du MFA.
On s'est rendu compte que beaucoup le faisaient ...

**Comment by Alexandre-Boisseau** [comment]
Bonjour,
Nous encourageons cette demande : permettre d'interdire l'utilisation de certains domaines, en l’occurrence ceux de nos établissements.

**Comment by floriannari** [comment]
Bonjour,
Je viens d'implémenter cette évolution sur la branche [develop](https://github.com/EsupPortail/esup-otp-manager/commits/develop/) 
J'en ai profité pour faire un peu de refactor pour que ce soit propre : https://github.com/EsupPortail/esup-otp-manager/compare/2537cbe...develop?w=1

Je pousserais sur master (avec un nouveau tag / release) dans quelques jours (le temps de détecter d'éventuels bugs sur nos serveurs)

**Comment by floriannari** [comment]
C'est maintenant disponible en v1.5.0

Pour cela @Alexandre-Boisseau , vous pouvez remplacer la ligne 
```json
        "#mail": "^(?!.*(?:univ[.]fr|univ-paris[.]fr)$).*$"
```
par
```
        "mail": "^(?!.*(?:univ-brest[.]fr)$).*$"
```

**Comment by Alexandre-Boisseau** [comment]
Bonjour et merci pour cette évolution.
Nous l'avons installée et fonctionne bien.
