### ISSUE TITLE
[BUG ?] `/` obligatoire a la fin de la `casBaseURL`

### ISSUE THREAD

**Issue by nothing-fr** [EsupPortail/esup-otp-manager#30]
Bonjour,

Lorsque nous configurons la `casBaseURL`, nous sommes obligés d'ajouter un `/` à la fin de l'URL.
Si nous ne le faisons pas, la dernière partie de l'url ne semble pas prise en compte.
Par exemple :
- `https://moncas.mondomaine.fr/cas`
Sans le `/` a la fin, l'url est prise comme : `https://moncas.mondomaine.fr` et me redirige donc sur une mauvaise URL CAS, j'ai donc un 404.

Vous me direz, ajoute le `/` a la fin de l'URL dans ce cas...

Sauf que cela pose soucis ensuite avec le logout d'OTP Manager, car l'url générée est alors : `https://moncas.mondomaine.fr//logout` ce qui ne plait pas a CAS. 

Je dois donc actuellement modifier le fichier `route.js` et changer : 

```diff
    router.get('/logout', function(req, res, next) {
        req.logout(function(err) {
            if (err) { return next(err); }
-            res.redirect(properties.esup.CAS.casBaseURL+'/logout');
+            res.redirect(properties.esup.CAS.casBaseURL+'logout');
          });
    });
```
Est-ce que je fait quelque chose de mal niveau de la configuration ? cela me semble étrange que personne d'autre ce trouve face a ce problème.

Cordialement.

**Comment by prigaux** [comment]
Bonjour, 

Vous pouvez faire un pull request avec la modif :-)

NB : chez nous, le double slash ne pose pas de pb https://cas.univ-paris1.fr/cas//logout

**Comment by nothing-fr** [comment]
> Bonjour,
> 
> Vous pouvez faire un pull request avec la modif :-)
> 
> NB : chez nous, le double slash ne pose pas de pb https://cas.univ-paris1.fr/cas//logout

Chez nous Erreur 500 : 
```java
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
```
